// Generate a static, SEO-friendly builds site from meta.json into ./docs, served
// by GitHub Pages. One page per champion (ranks for "<champ> build" searches) plus
// a searchable index. Regenerated by the daily workflow, so it never goes stale and
// costs zero ongoing effort. Every page funnels to the free app + the Discord.
//
//   node scripts/build-site.mjs

import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const DD = "https://ddragon.leagueoflegends.com";
const DOWNLOAD = "https://github.com/gutbolez/minmax-coach-releases/releases/latest";
const DISCORD = "https://discord.gg/RXK9YhKQGX";
const SITE = "Min-Max Coach";
const root = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const outDir = path.join(root, "docs");

const meta = JSON.parse(readFileSync(path.join(root, "meta.json"), "utf8"));
const patch = meta.patch || "";
const tier = (meta.tier || "diamond_plus")
  .replace(/_plus$/, "+")
  .replace(/_/g, " ")
  .replace(/^\w/, (c) => c.toUpperCase()); // "diamond_plus" -> "Diamond+"

const getJson = async (u) => {
  const r = await fetch(u, { headers: { "user-agent": "minmax-coach-site/1.0" } });
  if (!r.ok) throw new Error(`HTTP ${r.status} ${u}`);
  return r.json();
};

const esc = (s) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]/g, "");

const CSS = `
:root{--bg:#060D14;--panel:#0A141D;--line:#1B2A36;--ink:#F0E6D2;--steel:#8FA3B5;--dim:#5B6B7B;--cyan:#39C5CF;--gold:#C8A24B}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 system-ui,Segoe UI,Roboto,sans-serif}
a{color:var(--cyan);text-decoration:none}a:hover{text-decoration:underline}
.wrap{max-width:1000px;margin:0 auto;padding:20px}
header.top{display:flex;align-items:center;gap:10px;padding:14px 20px;border-bottom:1px solid var(--line);position:sticky;top:0;background:var(--bg);z-index:5}
header.top .dot{width:9px;height:9px;border-radius:2px;background:var(--cyan)}
header.top b{letter-spacing:.14em;text-transform:uppercase;font-size:13px}
header.top .sp{flex:1}
.btn{display:inline-block;padding:8px 14px;border-radius:6px;font-weight:600;font-size:13px}
.btn.gold{background:var(--gold);color:#12100a}.btn.ghost{border:1px solid var(--cyan);color:var(--cyan)}
.cta{display:flex;flex-wrap:wrap;gap:10px;align-items:center;background:linear-gradient(90deg,#0d1a24,#0a141d);border:1px solid var(--line);border-radius:10px;padding:16px;margin:18px 0}
.cta .grow{flex:1;min-width:220px}.cta h2{margin:0 0 4px;font-size:16px}.cta p{margin:0;color:var(--steel);font-size:13px}
h1{font-size:26px;margin:8px 0 2px}.sub{color:var(--dim);font-size:13px;margin-bottom:8px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(112px,1fr));gap:10px}
.champ{display:flex;flex-direction:column;align-items:center;gap:6px;padding:10px 6px;border:1px solid var(--line);border-radius:8px;background:var(--panel)}
.champ img{width:56px;height:56px;border-radius:8px}.champ span{font-size:12px;color:var(--steel);text-align:center}
.row{display:flex;gap:14px;flex-wrap:wrap}
.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:14px;margin:12px 0}
.card h3{margin:0 0 8px;font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:var(--cyan)}
.items{display:flex;gap:6px;flex-wrap:wrap;align-items:center}
.items img{width:40px;height:40px;border-radius:6px;border:1px solid var(--line)}
.pill{display:inline-block;background:#0d1a24;border:1px solid var(--line);border-radius:5px;padding:2px 8px;font-size:12px;color:var(--ink);margin:2px 4px 2px 0}
.ctr{display:flex;justify-content:space-between;border-bottom:1px solid var(--line);padding:6px 0;font-size:13px}
.ctr b{color:#E0533D}
footer{color:var(--dim);font-size:12px;border-top:1px solid var(--line);margin-top:24px;padding:16px 0}
.search{width:100%;padding:10px 12px;background:var(--panel);border:1px solid var(--line);border-radius:8px;color:var(--ink);font-size:14px;margin:6px 0 14px}
`;

const head = (title, desc, rel) => `<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<link rel="stylesheet" href="${rel}styles.css">
</head><body>
<header class="top"><span class="dot"></span><b><a href="${rel}index.html" style="color:inherit">${SITE}</a></b><span class="sp"></span>
<a class="btn ghost" href="${DISCORD}">Discord</a><a class="btn gold" href="${DOWNLOAD}">Download free</a></header>`;

const cta = `<div class="cta"><div class="grow"><h2>Get all of this live, in your game</h2>
<p>Min-Max Coach is a free ~3MB app that calls the build, runes, skill order and next move in real time. No account, nothing leaves your PC, and it can't get you banned.</p></div>
<a class="btn gold" href="${DOWNLOAD}">Download free</a><a class="btn ghost" href="${DISCORD}">Join the Discord</a></div>`;

const foot = `<footer>Data from Diamond+ ranked (patch ${esc(patch)}), refreshed daily. Not endorsed by or affiliated with Riot Games. Builds & runes via lolalytics, counters via op.gg, roster via Riot Data Dragon.</footer></body></html>`;

async function main() {
  const ver = (await getJson(`${DD}/api/versions.json`))[0];
  const champData = (await getJson(`${DD}/cdn/${ver}/data/en_US/champion.json`)).data;
  const items = (await getJson(`${DD}/cdn/${ver}/data/en_US/item.json`)).data;
  const itemName = (id) => (items[id] ? items[id].name : `Item ${id}`);
  const itemIcon = (id) => `${DD}/cdn/${ver}/img/item/${id}.png`;
  // name -> ddragon id (for icons/slugs)
  const nameToId = {};
  for (const c of Object.values(champData)) nameToId[c.name] = c.id;
  const champIcon = (name) => `${DD}/cdn/${ver}/img/champion/${nameToId[name] || name}.png`;

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(path.join(outDir, "champion"), { recursive: true });
  writeFileSync(path.join(outDir, "styles.css"), CSS.trim() + "\n");
  writeFileSync(path.join(outDir, ".nojekyll"), "");

  const names = Object.keys(meta.champions).filter((n) => nameToId[n]).sort();

  // Per-champion pages.
  for (const name of names) {
    const m = meta.champions[name];
    const core = (m.core || []).filter((id) => items[id]);
    const itemsHtml = core.length
      ? `<div class="items">${core.map((id) => `<img src="${itemIcon(id)}" alt="${esc(itemName(id))}" title="${esc(itemName(id))}" loading="lazy">`).join("")}</div>`
      : "<p class=sub>No core build data.</p>";
    const counters = (m.counters || [])
      .map((c) => `<div class="ctr"><span>${esc(c.c)}</span><b>${c.wr}% vs ${esc(name)}</b></div>`)
      .join("");
    const desc = `${name} build, runes, skill order and counters for patch ${patch} (${tier}). ${m.keystone ? "Keystone " + m.keystone + ". " : ""}${m.skill ? "Max " + m.skill + "." : ""}`;
    const body = `<div class="wrap">
<h1><img src="${champIcon(name)}" alt="${esc(name)}" width="40" height="40" style="border-radius:8px;vertical-align:middle;margin-right:8px">${esc(name)} Build & Runes</h1>
<div class="sub">Patch ${esc(patch)} · ${esc(tier)} ranked · refreshed daily</div>
${cta}
<div class="row">
<div class="card" style="flex:1;min-width:280px"><h3>Core build</h3>${itemsHtml}
${m.boots && items[m.boots] ? `<p class=sub style="margin-top:8px">Boots: ${esc(itemName(m.boots))}</p>` : ""}
${m.starting ? `<p class=sub>Start: ${esc(m.starting)}</p>` : ""}</div>
<div class="card" style="flex:1;min-width:280px"><h3>Runes & setup</h3>
${m.keystone ? `<div><span class="pill">${esc(m.keystone)}</span></div>` : ""}
${m.runes ? `<p class=sub style="margin-top:6px">${esc(m.runes)}</p>` : ""}
${m.shards ? `<p class=sub>Shards: ${esc(m.shards)}</p>` : ""}
${m.skill ? `<p style="margin-top:6px">Skill max order: <b style="color:var(--gold)">${esc(m.skill)}</b></p>` : ""}
${m.summoners ? `<p class=sub>Summoners: ${esc(m.summoners)}</p>` : ""}</div>
</div>
${counters ? `<div class="card"><h3>${esc(name)} is countered by</h3>${counters}</div>` : ""}
${cta}
</div>`;
    writeFileSync(
      path.join(outDir, "champion", `${slug(name)}.html`),
      head(`${name} Build, Runes & Counters (Patch ${patch}, ${tier}) — ${SITE}`, desc, "../") + body + foot
    );
  }

  // Index.
  const cards = names
    .map((n) => `<a class="champ" href="champion/${slug(n)}.html"><img src="${champIcon(n)}" alt="${esc(n)}" loading="lazy"><span>${esc(n)}</span></a>`)
    .join("");
  const indexBody = `<div class="wrap">
<h1>League of Legends builds, runes & counters</h1>
<div class="sub">Every champion · patch ${esc(patch)} · ${esc(tier)} ranked · refreshed daily</div>
${cta}
<input class="search" id="q" placeholder="Search champion…" oninput="var v=this.value.toLowerCase();document.querySelectorAll('.champ').forEach(function(e){e.style.display=e.innerText.toLowerCase().includes(v)?'':'none'})">
<div class="grid" id="grid">${cards}</div>
</div>`;
  writeFileSync(
    path.join(outDir, "index.html"),
    head(
      `LoL Builds, Runes & Counters (Patch ${patch}, ${tier}) — ${SITE}`,
      `Free, always-current League of Legends builds, runes, skill orders and counters for every champion, from ${tier} ranked. Get them live in-game with the free Min-Max Coach app.`,
      ""
    ) + indexBody + foot
  );

  console.log(`Wrote docs/ site: ${names.length} champion pages + index (patch ${patch}).`);
}

main().catch((e) => { console.error(e); process.exit(1); });
